-- Script SQL para criação da tabela no Supabase (PostgreSQL)

create table estoque_mdf (
  id bigint generated by default as identity primary key,
  created_at timestamptz default now() not null,
  tipo text not null check (tipo in ('Chapa', 'Sobra')),
  cor text not null,
  espessura text not null,
  comprimento integer not null check (comprimento > 0),
  largura integer not null check (largura > 0),
  quantidade integer not null default 1 check (quantidade >= 0),
  observacoes text
);

-- Habilitar Row Level Security (RLS) se desejado ou desabilitar para testes rápidos
-- Por padrão, para facilitar o uso interno simples, você pode deixar livre ou criar políticas de acesso.
alter table estoque_mdf enable row level security;

-- Política de acesso para permitir leitura pública / anônima (ou autenticada)
create policy "Permitir leitura de todos" on estoque_mdf
  for select using (true);

-- Política de acesso para permitir inserção
create policy "Permitir inserção" on estoque_mdf
  for insert with check (true);

-- Política de acesso para permitir atualização
create policy "Permitir atualização" on estoque_mdf
  for update using (true);

-- Política de acesso para permitir exclusão
create policy "Permitir exclusão" on estoque_mdf
  for delete using (true);
